### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by mibe** [MicrosoftDocs/office-developer-exchange-docs#127]
The link to the Exchange 2013 bandwith logging transport agent on line 21 is dead:

https://github.com/MicrosoftDocs/office-developer-exchange-docs/blame/master/docs/transport-agents/how-to-create-a-routingagent-transport-agent-for-exchange-2013.md#L21

**Comment by edwardforgacs** [comment]
Yep, all links are dead. If anyone does find the original download I'd be interested too.

**Comment by lindalu-MSFT** [comment]
Please include the doc that has the dead link so I can research and correct.

**Comment by lindalu-MSFT** [comment]
I updated the doc to point to the code sample repos here:
https://docs.microsoft.com/exchange/client-developer/transport-agents/transport-agent-code-samples-for-exchange-2013

**Comment by edwardforgacs** [comment]
The links are NOT FIXED. Not the original link nor any of the links on the page you posted on docs.microsoft.com.

This would have to be one of the most egregious examples of Microsoft "getting the KPIs up" while doing nothing.

Every single link on the page posted above goes to a generic "Browse Code Samples" page where it is impossible to actually find the code samples being referred to. I doubt the samples exist on that site because I have looked quite carefully in the past. It would be expected that each of those links points to the actual SPECIFIC sample which they did originally.

This is just worse than useless because it simply "hides" the problem that the links are broken, without actually fixing the links.

The original broken link was "Exchange 2013: Build a bandwidth logging transport agent" on this page:
https://github.com/MicrosoftDocs/office-developer-exchange-docs/blame/master/docs/transport-agents/how-to-create-a-routingagent-transport-agent-for-exchange-2013.md#L21

Which points here and results in a 404:
https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/master/exchange/client-developer/transport-agents/transport-agent-code-samples-for-exchange-2013.md

**Comment by mibe** [comment]
@lindalu-MSFT, yeah, as @edwardforgacs already said, the links are not really fixed, they get redirected to the generic "[Browse code samples](https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples)" site, where you find zero results for e.g. "bandwidth agent". This issue should be reopened IMHO...

**Comment by lindalu-MSFT** [comment]
@mibe @edwardforgacs Sadly we no longer have a team to maintain this content. I think your best bet is to go to Stack Overflow and ask the developer community there. I'm not even sure where these code samples are or if they even exist anymore. If you do find out anything that we could use to improve our content, you could add it to the repo and then open a PR. I can help with publishing; I just don't have bandwidth or skills to develop new code samples. Thanks for reaching out.

**Comment by mibe** [comment]
I understand. Maybe it's better to remove the [Transport agent code samples for Exchange 2013](https://docs.microsoft.com/en-us/exchange/client-developer/transport-agents/transport-agent-code-samples-for-exchange-2013) page completely then?

**Comment by lindalu-MSFT** [comment]
@mibe great suggestion, will do that. Thanks for reaching out!
