### ISSUE TITLE
How do we work with folders that don't have distinguished names

### ISSUE THREAD

**Issue by doubledrat** [MicrosoftDocs/office-developer-exchange-docs#51]
office-developer-exchange-docs/docs/exchange-web-services/how-to-work-with-folders-by-using-ews-in-exchange.md

every example I've found for listing folder contents uses distinguished names
how do I list the contents of a folder based on it's ID?!
I have a folder that I created and need to be able to enumerate it's contents using XML

**Comment by lindalu-MSFT** [comment]
@doubledrat Hey, so sorry for the late reply on your Issue. Sadly, we're not monitoring this repo closely anymore. I just happened across this issue. However, since this is a question and not an actual doc bug, we suggest you go to [StackOverflow tagged "exchangewebservices"](https://stackoverflow.com/questions/tagged/exchangewebservices) and ask your question to a developer there. You're far more likely to get a response! I'm going to close this issue, for now. If you feel it's a bug, please feel free to reactivate. Again, sorry for the late reply. I'll try to find an Exchange PM to see if there's anyone available to monitor this repo in the future.
